package com.hubciti.common.utility;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.StringReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

import com.hubciti.common.constants.HubCitiConstants;
import com.hubciti.common.pojos.CouponDetails;
import com.hubciti.common.pojos.CustomerInfo;
import com.hubciti.common.pojos.EventDetails;
import com.hubciti.common.pojos.Fundraiser;
import com.hubciti.common.pojos.HotDealsDetails;
import com.hubciti.common.pojos.Item;
import com.hubciti.common.pojos.ProductDetail;
import com.hubciti.common.pojos.RetailerDetail;
import com.hubciti.common.pojos.RetailersDetails;
import com.hubciti.common.pojos.Table;
import com.hubciti.common.pojos.UserDetails;

public class Utility {

	
	
	public static final String autoGeneratedPswd = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	
	/**
	 * Getting the logger instance.
	 */

	private static final Logger LOG = LoggerFactory.getLogger(Utility.class);

	/**
	 * The constant for &#x0.
	 */
	private static final char[] NULL = "&#x0;".toCharArray();

	/**
	 * The constant for &amp.
	 */
	private static final char[] AMP = "&amp;".toCharArray();

	/**
	 * The constant for &lt.
	 */
	private static final char[] LT = "&lt;".toCharArray();

	/**
	 * The constant for &gt.
	 */
	private static final char[] GT = "&gt;".toCharArray();

	/**
	 * The constant for &quot.
	 */
	private static final char[] QUOT = "&quot;".toCharArray();

	/**
	 * The constant for &apos.
	 */
	private static final char[] APOS = "&apos;".toCharArray();

	/**
	 * The constant for HTML Praragraph opening tag.
	 */

	private static final char[] HTMLPARAGRAPHOPEN = "<p>".toCharArray();
	/**
	 * The constant for HTML Praragraph Closing tag.
	 */

	private static final char[] HTMLPARAGRAPHCLOSE = "</p>".toCharArray();
	/**
	 * The constant for HTML Bold Opening tag.
	 */
	private static final char[] HTMLBOLDOPEN = "<b>".toCharArray();

	/**
	 * The constant for HTML Bold Closing tag.
	 */
	private static final char[] HTMLBOLDCLOSE = "</b>".toCharArray();
	/**
	 * The constant for HTML Break tag.
	 */
	private static final char[] HTMLBREAKCLOSE = "<br/>".toCharArray();

	/**
	 * The constant for HTML Break tag.
	 */
	private static final char[] HTMLBREAK = "<br>".toCharArray();

	/**
	 * The constant for HTML List Open tag.
	 */
	private static final char[] HTMLLISTITEMOPEN = "<li>".toCharArray();
	/**
	 * The constant for HTML List closing tag.
	 */
	private static final char[] HTMLLISTITEMCLOSE = "</li>".toCharArray();
	/**
	 * The constant for HTML Unordered List Opening tag.
	 */
	private static final char[] HTMUNORDEREDLISTOPEN = "<ul>".toCharArray();

	/**
	 * The constant for HTML Unordered List Closing tag.
	 */
	private static final char[] HTMLUNORDEREDLISTCLOSE = "</ul>".toCharArray();

	/**
	 * The constant for Carriage return Unordered List Closing tag.
	 */
	private static final char[] CARRIAGERETURN = "\r".toCharArray();

	/**
	 * The constant for Carriage return Unordered List Closing tag.
	 */
	private static final char[] NEWLINE = "\n".toCharArray();

	/**
	 * Created for Geo code sensor parameter
	 */
	public static final String SENSOR = "true";

	public static final String[] XML_ILLEGAL_CHAR = {"&", "<"};

	/**
	 * this method returns the xml String for the given Values.
	 * 
	 * @param errorCode
	 *            The error code.
	 * @param errorResponse
	 *            The error response.
	 * @return response with formed response.
	 */
	public static String formResponseXml(String errorCode, String errorResponse) {
		// final String methodName = "formResponseXml";
		// LOG.info(HubCitiConstants.METHODSTART + methodName);
		final StringBuilder response = new StringBuilder();
		response.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		response.append("<response>");
		response.append("<responseCode>");
		response.append(errorCode);
		response.append("</responseCode>");
		response.append("<responseText>");
		response.append(errorResponse);
		response.append("</responseText>");
		response.append("</response>");
		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return response.toString();
	}

	/**
	 * this method returns the xml String for the given Values.
	 * 
	 * @param errorCode
	 *            The error code.
	 * @param errorResponse
	 *            The error response.
	 * @return response with formed response.
	 */
	public static String formResponseXml(String errorCode, String errorResponse, String paramNode3, String paramValue3) {
		final StringBuilder response = new StringBuilder();
		response.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		response.append("<response>");
		response.append("<responseCode>");
		response.append(errorCode);
		response.append("</responseCode>");
		response.append("<responseText>");
		response.append(errorResponse);
		response.append("</responseText>");
		response.append("<" + paramNode3 + ">");
		response.append(paramValue3);
		response.append("</" + paramNode3 + ">");
		response.append("</response>");
		return response.toString();
	}

	/**
	 * The method to remove the special characters.
	 * 
	 * @param inPutXml
	 *            The input xml.
	 * @return the xml with special charcters removed.
	 */

	public static String removeSpecialChars(String inPutXml) {

		/*
		 * final String methodName = "removeSpecialChars";
		 * LOG.info(HubCitiConstants.METHODSTART + methodName);
		 */

		String outPutxML = "";
		if (null != inPutXml) {
			outPutxML = null;
			outPutxML = inPutXml.replaceAll(new String(AMP), "&");
			outPutxML = outPutxML.replaceAll(new String(GT), ">");
			outPutxML = outPutxML.replaceAll(new String(LT), "<");
			outPutxML = outPutxML.replaceAll(new String(NULL), "null");
			// outPutxML = outPutxML.replaceAll(new String(QUOT), "\"\"");
			outPutxML = outPutxML.replaceAll(new String(QUOT), "\"");
			outPutxML = outPutxML.replaceAll(new String(APOS), "'");
			outPutxML = outPutxML.replaceAll("\n", "");
			outPutxML = outPutxML.replaceAll("&#xd;", "\r");
			outPutxML = outPutxML.replaceAll("&#39;", "'");
		}
		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return outPutxML;
	}

	/**
	 * This method is used to remove special characters.
	 * 
	 * @param inPutXml
	 *            -As parameter
	 * @return outPutxML
	 */
	public static String removeSpecialCharsReverse(String inPutXml) {

		/*
		 * final String methodName = "removeSpecialChars";
		 * LOG.info(HubCitiConstants.METHODSTART + methodName);
		 */

		String outPutxML = "";
		if (null != inPutXml) {
			outPutxML = null;
			outPutxML = inPutXml.replaceAll("&", new String(AMP));
			outPutxML = outPutxML.replaceAll("'", new String(APOS));
			// outPutxML = outPutxML.replaceAll( "<" , new String(LT));
			/*
			 * outPutxML = outPutxML.replaceAll(new String(GT), ">"); outPutxML
			 * = outPutxML.replaceAll(new String(LT), "<"); outPutxML =
			 * outPutxML.replaceAll(new String(NULL), "null"); outPutxML =
			 * outPutxML.replaceAll(new String(QUOT), "\"\""); outPutxML =
			 * outPutxML.replaceAll(new String(APOS), "'");
			 */
			// outPutxML = outPutxML.replaceAll("\n", "");
		}
		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return outPutxML;
	}

	public static String checkNull(String strValue) {
		// if (null == strValue || strValue.equals("null") || strValue == "null"
		// || "".equals(strValue)) {
		if (null == strValue || strValue.equals("null") || "".equals(strValue)) {
			return "";
		} else {
			return strValue.trim();
		}
	}

	/**
	 * Utility method for forming ForgotPassword Email Template HTMl.
	 * 
	 * @param password
	 *            The password.
	 * @return mailData The email template for Forgot password.
	 */

	public static String forgotPasswordEmailTemplate(String password) {

		LOG.info("Inside Utility : forgotPasswordEmailTemplate");
		final String mailData = "<html><head></head><body><p>Here is the account information that you requested.<br/>Your password: "
				+ "<b>"
				+ password
				+ "</b><br/><br/>Log in now:<br/>http://www.hubcitiapp.com or through your application.<br/><br/>Please note:  For your account security, we only provide your password in this email. "
				+ "Once you have logged in to your account, you can change your password. To keep your account secure, we recommend that you delete this email and keep a copy of your log-in name"
				+ " and password in a secure place.<br/><br/>If you have any additional questions about your account log-in, reply to this email or email us at support@hubciti.com. For the fastest response, please include the text of this message along with your"
				+ " question.<br/><br/></p><p>Sincerely,<br/>HubCiti Team</p></body></html>";
		return mailData;
	}
	


	

	public static String forgotPasswordEmailTemplate_v2(String userName,String password) {
		LOG.info("Inside Utility : forgotPasswordEmailTemplate_v2");

		final String mailData = "<html><head></head><body>"
				+ "<p> Hi "
				+ "<b>"+userName+"</b>"
				+ ","
				+ "<p>We've sent information about resetting your password. Please find the username and auto generated password to login.<br/> <br/>"
				+ " UserName: "
				+ "<b>"
				+ userName
				+ "</b><br/>"
				+ " Password: "
				+ "<b>"
				+ password
				+ "</b></p></p>"
				+"<p><b>Note:</b> This Auto generated password will be valid only for 30 minutes.</p>"
				+"<p>Sincerely,<br/>HubCiti Team</p></body></html>";
		LOG.info("Exiting Utility : forgotPasswordEmailTemplate_v2");
		return mailData;
	}
	
	/**
	 * This method takes any number and sets precision of 2 decimal with
	 * rounding.
	 * 
	 * @param value
	 *            values which will be formated.
	 * @return value formated values.
	 */
	public static String formatDecimalValue(String value) {
		if (null != value && !"".equals(value) && !(value.equals(HubCitiConstants.NOTAPPLICABLE))) {
			final Double price = new Double(value);
			final DecimalFormat df = new DecimalFormat("########0.00");
			value = df.format(price);
		} else {
			value = HubCitiConstants.NOTAPPLICABLE;
		}
		return value;
	}

	public static String removeHTMLTags(String inPutXml) {
		String outPutxML = "";
		if (null != inPutXml) {
			outPutxML = null;
			outPutxML = inPutXml.replaceAll(new String(HTMLPARAGRAPHOPEN), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLPARAGRAPHCLOSE), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLBREAK), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLBREAKCLOSE), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLLISTITEMOPEN), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLLISTITEMCLOSE), "");
			outPutxML = outPutxML.replaceAll(new String(HTMUNORDEREDLISTOPEN), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLUNORDEREDLISTCLOSE), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLBOLDOPEN), "");
			outPutxML = outPutxML.replaceAll(new String(HTMLBOLDCLOSE), "");
			outPutxML = outPutxML.replaceAll(new String(CARRIAGERETURN), "");
			outPutxML = outPutxML.replaceAll(new String(NEWLINE), "");
		}
		return outPutxML;
	}

	/**
	 * The method to get the current date formated in yyyy-MM-dd HH:mm:ss
	 * format.
	 * 
	 * @param dbdate
	 *            -As parameter
	 * @return The current date formatted in yyyy-MM-dd HH:mm:ss forma
	 */

	public static String convertDBdate(String dbdate) {
		// LOG.info("Inside Utility : convertDBdate");
		String javaDate = null;
		try {
			SimpleDateFormat formatter, FORMATTER;
			// formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
			formatter = new SimpleDateFormat("yyyy-MM-dd");
			Date date = formatter.parse(dbdate);
			FORMATTER = new SimpleDateFormat("MM-dd-yyyy");
			// LOG.info("NewDate-->" + FORMATTER.format(date));
			javaDate = FORMATTER.format(date);
		} catch (ParseException exception) {
			LOG.info("Exception in convertDBdate method" + exception.getMessage());
			return null;
		}
		return javaDate;
	}

	/**
	 * The method to change date format from MM-dd-yyyy to EEE, d MMM yyyy
	 * (12-31-2013 to Wed, 31 Jan 2013).
	 * 
	 * @param string
	 *            containing date.
	 * @return formated date as string.
	 */
	public static String changeDateFormat1(String requestDate) {
		// LOG.info("Inside Utility : changeDateFormat1");
		String formattedDate = null;
		try {
			SimpleDateFormat formatter, FORMATTER;
			formatter = new SimpleDateFormat("MM-dd-yyyy");
			Date date = formatter.parse(requestDate);
			FORMATTER = new SimpleDateFormat("EEE, d MMM yyyy");
			formattedDate = FORMATTER.format(date);
		} catch (ParseException exception) {
			LOG.info("Exception in convertDBdate method" + exception.getMessage());
			return null;
		}
		return formattedDate;
	}

	/**
	 * The method to get the time formated in h:mm AM/PM
	 * 
	 * @param dbTime
	 *            -As parameter
	 * @return The time formatted in h:mm AM/PM
	 */
	public static String convertDBtime(String time) {
		// LOG.info("Inside Utility : convertDBtime");
		String formatedTime = null;
		try {
			SimpleDateFormat formatter, FORMATTER;
			formatter = new SimpleDateFormat("HH:mm:ss");
			Date date = formatter.parse(time);
			FORMATTER = new SimpleDateFormat("HH:mm");
			formatedTime = FORMATTER.format(date);
		} catch (ParseException exception) {
			LOG.info("Exception in convertDBtime method" + exception.getMessage());
			return null;
		}
		return formatedTime;
	}

	/**
	 * The method to get the time formated in h:mm AM/PM
	 * 
	 * @param dbTime
	 *            -As parameter
	 * @return The time formatted in h:mm AM/PM
	 */
	public static String convertDBtimeAmPm(String time) {
		// LOG.info("Inside Utility : convertDBtime");
		String formatedTime = null;
		try {
			SimpleDateFormat formatter, FORMATTER;
			formatter = new SimpleDateFormat("HH:mm");
			Date date = formatter.parse(time);
			FORMATTER = new SimpleDateFormat("hh:mm a");
			formatedTime = FORMATTER.format(date);
		} catch (ParseException exception) {
			LOG.info("Exception in convertDBtime method" + exception.getMessage());
			return null;
		}
		return formatedTime;
	}

	/**
	 * This method is used to round the values to nearest value.
	 * 
	 * @param distance
	 *            -As String parameter
	 * @return distance rounded value
	 */
	public static String roundNearestValues(String distance) {
		if (null != distance && !"".equals(distance)) {
			try {
				final Float fltDistance = new Float(distance);
				distance = String.valueOf(Math.round(fltDistance));
			} catch (NumberFormatException exception) {
				LOG.info("Exception in roundNearestValues method" + exception.getMessage());
				distance = HubCitiConstants.NOTAPPLICABLE;
			}

		} else {
			distance = HubCitiConstants.NOTAPPLICABLE;
		}
		return distance;
	}

	/**
	 * This method is used to form xml.
	 * 
	 * @param rootTag
	 *            -The root tag
	 * @param responseMap
	 *            -As parameter
	 * @return response
	 */
	public static String formResponseXml(String rootTag, Map<String, String> responseMap) {
		/*
		 * final String methodName = "formResponseXml";
		 * LOG.info(HubCitiConstants.METHODSTART + methodName);
		 */
		Iterator<String> itr = responseMap.keySet().iterator();
		final StringBuilder response = new StringBuilder();
		response.append("<" + rootTag + ">");
		while (itr.hasNext()) {
			String key = itr.next();
			String value = responseMap.get(key);
			response.append("<" + key + ">");
			response.append(value);
			response.append("</" + key + ">");
		}
		response.append("</" + rootTag + ">");
		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return response.toString();
	}

	/**
	 * The method to get the current date formated in yyyy-MM-dd HH:mm:ss
	 * format.
	 * 
	 * @return The current date formatted in yyyy-MM-dd HH:mm:ss forma
	 * @throws java.text.ParseException
	 *             The exception of type java.text.ParseException
	 */

	public static java.sql.Timestamp getFormattedDate() throws java.text.ParseException {
		// LOG.info("Inside Utility : getFormattedDate");
		final Date date = new Date();
		java.sql.Timestamp sqltDate = null;
		final DateFormat formater = new SimpleDateFormat("MM-dd-yyyy");
		java.util.Date parsedUtilDate;
		parsedUtilDate = formater.parse(formater.format(date));
		sqltDate = new java.sql.Timestamp(parsedUtilDate.getTime());
		return sqltDate;
	}

	/**
	 * The method to get the current date formated in yyyy-MM-dd HH:mm:ss
	 * format.
	 * 
	 * @return The current date formatted in yyyy-MM-dd HH:mm:ss forma
	 */
	public static String getFormattedCurrentDate() {
		/*
		 * final String methodName = "getFormattedDate";
		 * LOG.info(HubCitiConstants.METHODSTART + methodName);
		 */

		final Date date = new Date();
		/*
		 * formatting the current date.
		 */
		String currentDateStr = null;
		try {
			final DateFormat formater = new SimpleDateFormat("MM-dd-yyyy");
			final Date parsedUtilDate = formater.parse(formater.format(date));
			currentDateStr = formater.format(parsedUtilDate);
		} catch (ParseException exception) {
			LOG.info("Exception in convertDBdate method" + exception.getMessage());
			return HubCitiConstants.NOTAPPLICABLE;
		}

		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return currentDateStr;
	}

	/**
	 * The method for null checks.
	 * 
	 * @param arg
	 *            the input string
	 * @return the response string.
	 */

	public static String nullCheck(String arg) {
		// final String methodName = "nullCheck";
		// LOG.info(HubCitiConstants.METHODSTART + methodName);

		if (null != arg && !"".equals(arg)) {
			arg.trim();
		}
		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return arg;
	}

	/**
	 * This method is used to check nulls.
	 * 
	 * @param arg
	 *            -As parameter
	 * @return arg
	 */
	public static String isNull(String arg) {
		// final String methodName = "isNull";
		// LOG.info(HubCitiConstants.METHODSTART + methodName);

		if (null != arg && !"".equals(arg)) {
			arg.trim();
		} else {
			arg = "";
		}
		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return arg;
	}

	/*
	 * // for geocode api public static String getGeocodePostalcode(String
	 * latlong) throws Exception { // url //
	 * =http://maps.googleapis.com/maps/api
	 * /geocode/xml?latlng=40.714224,-73.961452&sensor=true URL url = new
	 * URL(HubCitiConstants.GEOCODEURL + "latlng=" + latlong + "&sensor=" +
	 * SENSOR); LOG.info("URL is : " + url); URLConnection conn =
	 * url.openConnection(); ByteArrayOutputStream output = new
	 * ByteArrayOutputStream(1024); IOUtils.copy(conn.getInputStream(), output);
	 * output.close(); String postalCode = null; JSONObject jsonObj = new
	 * JSONObject(output.toString()); try { String Status =
	 * jsonObj.getString("status"); if (Status.equalsIgnoreCase("OK")) {
	 * JSONArray Results = jsonObj.getJSONArray("results"); JSONObject zero =
	 * Results.getJSONObject(0); JSONArray address_components = zero
	 * .getJSONArray("address_components"); for (int i = 0; i <
	 * address_components.length(); i++) { JSONObject zero2 =
	 * address_components.getJSONObject(i); String long_name =
	 * zero2.getString("long_name"); JSONArray mtypes =
	 * zero2.getJSONArray("types"); String Type = mtypes.getString(0); if
	 * (!long_name.equals(null) || long_name.length() > 0 || long_name != "") {
	 * if (Type.equalsIgnoreCase("postal_code")) { postalCode = long_name; } } }
	 * } } catch (Exception e) { e.printStackTrace(); } return postalCode; }
	 */

	public static String formResponseXml(String errorCode, String errorResponse, String addElementName, String addElementValue, String addElementName2, String addElementValue2,
			String addElementName3, String addElementValue3) {

		/*
		 * final String methodName = "formResponseXml";
		 * LOG.info(HubCitiConstants.METHODSTART + methodName);
		 */

		final StringBuilder response = new StringBuilder();
		response.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		response.append("<response>");
		response.append("<responseCode>");
		response.append(errorCode);
		response.append("</responseCode>");
		response.append("<responseText>");
		response.append(errorResponse);
		response.append("</responseText>");
		response.append("<" + addElementName + ">");
		response.append(addElementValue);
		response.append("</" + addElementName + ">");
		response.append("<" + addElementName2 + ">");
		response.append(addElementValue2);
		response.append("</" + addElementName2 + ">");
		response.append("<" + addElementName3 + ">");
		response.append(addElementValue3);
		response.append("</" + addElementName3 + ">");
		response.append("</response>");
		// LOG.info(HubCitiConstants.METHODEND + methodName);
		return response.toString();
	}

	/**
	 * The method for forming HTML with product Info.
	 * 
	 * @param productDetail
	 *            product object.
	 * @param retailerDetail
	 *            retailer object
	 * @param userId
	 *            int parameter
	 * @return The email template.
	 * @throws NoSuchAlgorithmException
	 *             Exception related to algorithm
	 * @throws NoSuchPaddingException
	 *             - Exception related to Padding
	 * @throws InvalidKeyException
	 *             - Exception related to InvalidKey
	 * @throws InvalidAlgorithmParameterException
	 *             - Exception related to InvalidAlgorithmParameter
	 * @throws InvalidKeySpecException
	 *             - Exception related to InvalidKeySpec
	 * @throws IllegalBlockSizeException
	 *             - Exception related to IllegalBlockSize
	 * @throws BadPaddingException
	 *             - Exception related to BadPaddings
	 */

	public static String formProductInfoHTML(List<ProductDetail> productDetail, RetailerDetail retailerDetail, int userId, String shareURL)
	/*
	 * public static String formProductInfoHTML(List<ProductDetail>
	 * productDetail)
	 */
	throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException,
			BadPaddingException {
		LOG.info("Inside Utility : formProductInfoHTML ");
		/*
		 * String productKey = null; String productId =
		 * Integer.toString(productDetail.get(0).getProductId());
		 */
		/*
		 * String decryptedUserId = Integer.toString(userId);
		 * 
		 * String key = decryptedUserId + "/" + productId; EncryptDecryptPwd
		 * enryptDecryptpwd = null; enryptDecryptpwd = new EncryptDecryptPwd();
		 * productKey = enryptDecryptpwd.encrypt(key);
		 */
		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body> <h4>" + productDetail.get(0).getShareText() + "</h4>\n");
		emailTemplate.append("<table border=\"0\">");
		/*
		 * emailTemplate.append("<tr><td width=\"300\" rowspan=\"7\">");
		 * 
		 * if (productDetail.get(0).getImagePath() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(productDetail.get(0).getImagePath())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * productDetail.get(0).getImagePath() + "\"/></tr>"); }
		 */
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Product Name:</b> " + productDetail.get(0).getShareProdName() + "</td></tr>");

		if (null != productDetail.get(0).getShareProdLongDesc() && !"N/A".equals(productDetail.get(0).getShareProdLongDesc())) {
			emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Product Information:</b> " + productDetail.get(0).getShareProdLongDesc() + "</td></tr>");
		}

		/*
		 * if (null != retailerDetail) {
		 * 
		 * emailTemplate.append(
		 * "<tr><td width=\"300\" height=\"36\"><b>Retailer Name:</b> " +
		 * retailerDetail.getRetailerName() + "</td></tr>");
		 * emailTemplate.append
		 * ("<tr><td width=\"300\" height=\"36\"><b>Address:</b> " +
		 * retailerDetail.getRetaileraddress1() + "," + retailerDetail.getCity()
		 * + "," + retailerDetail.getState() + "," +
		 * retailerDetail.getPostalCode() + "</td></tr>"); emailTemplate.append(
		 * "<tr><td width=\"300\" height=\"36\"><b>Sale Price:</b> " +
		 * retailerDetail.getSalePrice() + "</td></tr>"); }
		 * emailTemplate.append(
		 * "<tr><td width=\"300\" height=\"36\"><b>Manufacturer Name:</b> " +
		 * productDetail.get(0).getManufacturersName() + "</td></tr>");
		 * emailTemplate
		 * .append("<tr><td width=\"300\" height=\"36\"><b>Weight:</b> " +
		 * productDetail.get(0).getWeight() + "</td></tr>");
		 * emailTemplate.append
		 * ("<tr><td width=\"300\" height=\"36\"><b>Weight Units:</b> " +
		 * productDetail.get(0).getWeightUnits() + "</td></tr>");
		 * emailTemplate.append
		 * ("<tr><td width=\"300\" height=\"36\"><b>Product Expiration Date:</b> "
		 * + productDetail.get(0).getProductExpDate() + "</td></tr>");
		 */
		/*
		 * emailTemplate.append("</table>");
		 */
		if (null != productDetail.get(0).getQrUrl() && !productDetail.get(0).getQrUrl().equals("N/A")) {
			emailTemplate.append("<tr><td  height=\"36\"><b>Product URL : </b> <a href=\"" + Utility.getTinyURL(productDetail.get(0).getQrUrl()) + "\">"
					+ Utility.getTinyURL(productDetail.get(0).getQrUrl()) + "</a></td></tr>");
		}
		// emailTemplate.append("<tr><td><h4>More info <a href=\"" + shareURL +
		// "productKey=" + productKey + "\"/>Click here</a></h4></td></tr>\n");
		emailTemplate.append("<tr><td></td></tr>\n");
		/*
		 * if (productDetail.get(0).getScanseeimg() != null &&
		 * !HubCitiConstants.
		 * NOTAPPLICABLE.equals(productDetail.get(0).getScanseeimg())) {
		 * emailTemplate
		 * .append("<tr><td><img height=\"40\" width=\"150\" src=\"" +
		 * productDetail.get(0).getScanseeimg() + "\"/></td></tr>\n"); } if
		 * (productDetail.get(0).getFacebookimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(productDetail.get(0).getFacebookimg())) {
		 * emailTemplate.append("<tr><td><img height=\"50\" width=\"50\" src=\""
		 * + productDetail.get(0).getFacebookimg() + "\"/>\n"); } if
		 * (productDetail.get(0).getTwitterimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(productDetail.get(0).getTwitterimg())) {
		 * emailTemplate.append("<img  height=\"50\" width=\"50\" src=\"" +
		 * productDetail.get(0).getTwitterimg() + "\"/>"); } if
		 * (productDetail.get(0).getArrowscanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(productDetail.get(0).getArrowscanseeimg())) {
		 * emailTemplate.append("<img height=\"52\" width=\"52\" src=\"" +
		 * productDetail.get(0).getArrowscanseeimg() + "\"/></td></tr>\n"); }
		 */
		emailTemplate.append("<tr><td> more information at <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a></td></tr>");
		emailTemplate.append("</table>");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	/**
	 * The method for forming HTML with product Info.
	 * 
	 * @param productDetail
	 *            product object.
	 * @param retailerDetail
	 *            retailer object
	 * @param userId
	 *            int parameter
	 * @return The email template.
	 * @throws NoSuchAlgorithmException
	 *             Exception related to algorithm
	 * @throws NoSuchPaddingException
	 *             - Exception related to Padding
	 * @throws InvalidKeyException
	 *             - Exception related to InvalidKey
	 * @throws InvalidAlgorithmParameterException
	 *             - Exception related to InvalidAlgorithmParameter
	 * @throws InvalidKeySpecException
	 *             - Exception related to InvalidKeySpec
	 * @throws IllegalBlockSizeException
	 *             - Exception related to IllegalBlockSize
	 * @throws BadPaddingException
	 *             - Exception related to BadPaddings
	 */

	public static String formProductInfoHTML_ANDROID(List<ProductDetail> productDetail, RetailerDetail retailerDetail, int userId, String shareURL)
	/*
	 * public static String formProductInfoHTML(List<ProductDetail>
	 * productDetail)
	 */
	throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException,
			BadPaddingException {
		LOG.info("Inside Utility : formProductInfoHTML ");
		/*
		 * String productKey = null; String productId =
		 * Integer.toString(productDetail.get(0).getProductId());
		 */
		/*
		 * String decryptedUserId = Integer.toString(userId);
		 * 
		 * String key = decryptedUserId + "/" + productId; EncryptDecryptPwd
		 * enryptDecryptpwd = null; enryptDecryptpwd = new EncryptDecryptPwd();
		 * productKey = enryptDecryptpwd.encrypt(key);
		 */
		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body> <h4>" + productDetail.get(0).getShareText() + "</h4>\n");
		/* emailTemplate.append("<table border=\"0\">"); */
		/*
		 * emailTemplate.append("<tr><td width=\"300\" rowspan=\"7\">");
		 * 
		 * if (productDetail.get(0).getImagePath() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(productDetail.get(0).getImagePath())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * productDetail.get(0).getImagePath() + "\"/></tr>"); }
		 */
		emailTemplate.append("<p><b>Product Name:</b> " + productDetail.get(0).getShareProdName() + "</p>");

		if (null != productDetail.get(0).getShareProdLongDesc() && !"N/A".equals(productDetail.get(0).getShareProdLongDesc())) {
			emailTemplate.append("<p><b>Product Information:</b> " + productDetail.get(0).getShareProdLongDesc() + "</p>");
		}

		/*
		 * if (null != retailerDetail) {
		 * 
		 * emailTemplate.append(
		 * "<tr><td width=\"300\" height=\"36\"><b>Retailer Name:</b> " +
		 * retailerDetail.getRetailerName() + "</td></tr>");
		 * emailTemplate.append
		 * ("<tr><td width=\"300\" height=\"36\"><b>Address:</b> " +
		 * retailerDetail.getRetaileraddress1() + "," + retailerDetail.getCity()
		 * + "," + retailerDetail.getState() + "," +
		 * retailerDetail.getPostalCode() + "</td></tr>"); emailTemplate.append(
		 * "<tr><td width=\"300\" height=\"36\"><b>Sale Price:</b> " +
		 * retailerDetail.getSalePrice() + "</td></tr>"); }
		 * emailTemplate.append(
		 * "<tr><td width=\"300\" height=\"36\"><b>Manufacturer Name:</b> " +
		 * productDetail.get(0).getManufacturersName() + "</td></tr>");
		 * emailTemplate
		 * .append("<tr><td width=\"300\" height=\"36\"><b>Weight:</b> " +
		 * productDetail.get(0).getWeight() + "</td></tr>");
		 * emailTemplate.append
		 * ("<tr><td width=\"300\" height=\"36\"><b>Weight Units:</b> " +
		 * productDetail.get(0).getWeightUnits() + "</td></tr>");
		 * emailTemplate.append
		 * ("<tr><td width=\"300\" height=\"36\"><b>Product Expiration Date:</b> "
		 * + productDetail.get(0).getProductExpDate() + "</td></tr>");
		 */
		/*
		 * emailTemplate.append("</table>");
		 */
		if (null != productDetail.get(0).getQrUrl() && !productDetail.get(0).getQrUrl().equals("N/A")) {
			emailTemplate.append("<p><b>Product URL : </b> <a href=\"" + Utility.getTinyURL(productDetail.get(0).getQrUrl()) + "\">"
					+ Utility.getTinyURL(productDetail.get(0).getQrUrl()) + "</a></p>");
		}
		// emailTemplate.append("<tr><td><h4>More info <a href=\"" + shareURL +
		// "productKey=" + productKey + "\"/>Click here</a></h4></td></tr>\n");
		/* emailTemplate.append("<tr><td></td></tr>\n"); */
		/*
		 * if (productDetail.get(0).getScanseeimg() != null &&
		 * !HubCitiConstants.
		 * NOTAPPLICABLE.equals(productDetail.get(0).getScanseeimg())) {
		 * emailTemplate
		 * .append("<tr><td><img height=\"40\" width=\"150\" src=\"" +
		 * productDetail.get(0).getScanseeimg() + "\"/></td></tr>\n"); } if
		 * (productDetail.get(0).getFacebookimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(productDetail.get(0).getFacebookimg())) {
		 * emailTemplate.append("<tr><td><img height=\"50\" width=\"50\" src=\""
		 * + productDetail.get(0).getFacebookimg() + "\"/>\n"); } if
		 * (productDetail.get(0).getTwitterimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(productDetail.get(0).getTwitterimg())) {
		 * emailTemplate.append("<img  height=\"50\" width=\"50\" src=\"" +
		 * productDetail.get(0).getTwitterimg() + "\"/>"); } if
		 * (productDetail.get(0).getArrowscanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(productDetail.get(0).getArrowscanseeimg())) {
		 * emailTemplate.append("<img height=\"52\" width=\"52\" src=\"" +
		 * productDetail.get(0).getArrowscanseeimg() + "\"/></td></tr>\n"); }
		 */
		emailTemplate.append("<p> more information at <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a></p>");
		/*
		 * emailTemplate.append("</table>");
		 */emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	/**
	 * This method for sharing coupon information through mail.
	 * 
	 * @param shareCouponLst
	 *            contains coupon information
	 * @return response
	 */
	public static String formCouponInfoHTML(List<CouponDetails> shareCouponLst) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formCouponInfoHTML ");
		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		// emailTemplate.append("<body> <h4> I found this for you and thought you might be interested:</h4>\n");
		emailTemplate.append("<body> <h4> " + shareCouponLst.get(0).getShareText() + "</h4>\n");
		emailTemplate.append("<table border=\"0\">");

		if (null != shareCouponLst.get(0).getCouponName()) {
			emailTemplate.append("<tr><td  height=\"36\"><b>Deal Name:</b> " + shareCouponLst.get(0).getCouponName() + "</td></tr>");
		}
		if (null != shareCouponLst.get(0).getQrUrl() && !shareCouponLst.get(0).getQrUrl().equals("N/A")) {
			emailTemplate.append("<tr><td  height=\"36\"><b>Deal URL:</b> <a href=\"" + Utility.getTinyURL(shareCouponLst.get(0).getQrUrl()) + "\">"
					+ Utility.getTinyURL(shareCouponLst.get(0).getQrUrl()) + "</a></td></tr>");
		}

		/*
		 * if (null != shareCouponLst.get(0).getCouponImagePath() &&
		 * !shareCouponLst.get(0).getCouponImagePath().equals("N/A")) { String
		 * imagePath = shareCouponLst.get(0).getCouponImagePath(); // if
		 * (imagePath != "") { if (!imagePath.equals("")) { int index =
		 * imagePath.lastIndexOf('/'); if (index > 0) { String imageName =
		 * imagePath.substring(imagePath.lastIndexOf('/') + 1,
		 * imagePath.length()); if (!"imageNotFound.png".equals(imageName)) {
		 * emailTemplate.append(
		 * "<tr><td  height=\"36\"><b>Coupon Image:</b> <img height=\"40\" width=\"40\" src=\""
		 * + shareCouponLst.get(0).getCouponImagePath() + "\"/></td></tr>"); } }
		 * } }
		 */

		/*
		 * emailTemplate.append("<tr><td  height=\"36\"><b>Coupon Start Date:</b> "
		 * + shareCouponLst.get(0).getCouponStartDate() + "</td></tr>");
		 * emailTemplate
		 * .append("<tr><td  height=\"36\"><b>Coupon Expire Date:</b> " +
		 * shareCouponLst.get(0).getCouponExpireDate() + "</td></tr>");
		 * emailTemplate.append("</table>");
		 * emailTemplate.append("<tr><td></td></tr>\n"); if
		 * (shareCouponLst.get(0).getScanseeimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(shareCouponLst.get(0).getScanseeimg())) {
		 * emailTemplate.append
		 * ("<tr><td><img height=\"40\" width=\"150\" src=\"" +
		 * shareCouponLst.get(0).getScanseeimg() + "\"/></td></tr>\n"); } if
		 * (shareCouponLst.get(0).getFacebookimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(shareCouponLst.get(0).getFacebookimg())) {
		 * emailTemplate.append
		 * ("<tr><td><img height=\"50\" width=\"50\"  src=\"" +
		 * shareCouponLst.get(0).getFacebookimg() + "\"/>\n"); } if
		 * (shareCouponLst.get(0).getTwitterimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(shareCouponLst.get(0).getTwitterimg())) {
		 * emailTemplate.append("<img height=\"50\" width=\"50\" src=\"" +
		 * shareCouponLst.get(0).getTwitterimg() + "\"/>"); } if
		 * (shareCouponLst.get(0).getArrowscanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(shareCouponLst.get(0).getArrowscanseeimg())) {
		 * emailTemplate.append("<img  height=\"52\" width=\"52\" src=\"" +
		 * shareCouponLst.get(0).getArrowscanseeimg() + "\"/></td></tr>\n"); }
		 */
		emailTemplate.append("<tr><td></td></tr>");
		emailTemplate.append("<tr><td></td></tr>");
		emailTemplate.append("<tr><td> more information at <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a></td></tr>");
		emailTemplate.append("</table>");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	/**
	 * This method for sharing coupon information through mail.
	 * 
	 * @param shareCouponLst
	 *            contains coupon information
	 * @return response
	 */
	public static String formCouponInfoHTML_ANDROID(List<CouponDetails> shareCouponLst) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formCouponInfoHTML ");
		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		// emailTemplate.append("<body> <h4> I found this for you and thought you might be interested:</h4>\n");
		emailTemplate.append("<body> <h4> " + shareCouponLst.get(0).getShareText() + "</h4>\n");
		/*
		 * emailTemplate.append("<table border=\"0\">");
		 */
		if (null != shareCouponLst.get(0).getCouponName()) {
			emailTemplate.append("<p><b>Deal Name:</b> " + shareCouponLst.get(0).getCouponName() + "</p>");
		}
		if (null != shareCouponLst.get(0).getQrUrl() && !shareCouponLst.get(0).getQrUrl().equals("N/A")) {
			emailTemplate.append("<p><b>Deal URL:</b> <a href=\"" + Utility.getTinyURL(shareCouponLst.get(0).getQrUrl()) + "\">"
					+ Utility.getTinyURL(shareCouponLst.get(0).getQrUrl()) + "</a></p>");
		}

		/*
		 * if (null != shareCouponLst.get(0).getCouponImagePath() &&
		 * !shareCouponLst.get(0).getCouponImagePath().equals("N/A")) { String
		 * imagePath = shareCouponLst.get(0).getCouponImagePath(); // if
		 * (imagePath != "") { if (!imagePath.equals("")) { int index =
		 * imagePath.lastIndexOf('/'); if (index > 0) { String imageName =
		 * imagePath.substring(imagePath.lastIndexOf('/') + 1,
		 * imagePath.length()); if (!"imageNotFound.png".equals(imageName)) {
		 * emailTemplate.append(
		 * "<tr><td  height=\"36\"><b>Coupon Image:</b> <img height=\"40\" width=\"40\" src=\""
		 * + shareCouponLst.get(0).getCouponImagePath() + "\"/></td></tr>"); } }
		 * } }
		 */

		/*
		 * emailTemplate.append("<tr><td  height=\"36\"><b>Coupon Start Date:</b> "
		 * + shareCouponLst.get(0).getCouponStartDate() + "</td></tr>");
		 * emailTemplate
		 * .append("<tr><td  height=\"36\"><b>Coupon Expire Date:</b> " +
		 * shareCouponLst.get(0).getCouponExpireDate() + "</td></tr>");
		 * emailTemplate.append("</table>");
		 * emailTemplate.append("<tr><td></td></tr>\n"); if
		 * (shareCouponLst.get(0).getScanseeimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(shareCouponLst.get(0).getScanseeimg())) {
		 * emailTemplate.append
		 * ("<tr><td><img height=\"40\" width=\"150\" src=\"" +
		 * shareCouponLst.get(0).getScanseeimg() + "\"/></td></tr>\n"); } if
		 * (shareCouponLst.get(0).getFacebookimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(shareCouponLst.get(0).getFacebookimg())) {
		 * emailTemplate.append
		 * ("<tr><td><img height=\"50\" width=\"50\"  src=\"" +
		 * shareCouponLst.get(0).getFacebookimg() + "\"/>\n"); } if
		 * (shareCouponLst.get(0).getTwitterimg() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(shareCouponLst.get(0).getTwitterimg())) {
		 * emailTemplate.append("<img height=\"50\" width=\"50\" src=\"" +
		 * shareCouponLst.get(0).getTwitterimg() + "\"/>"); } if
		 * (shareCouponLst.get(0).getArrowscanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(shareCouponLst.get(0).getArrowscanseeimg())) {
		 * emailTemplate.append("<img  height=\"52\" width=\"52\" src=\"" +
		 * shareCouponLst.get(0).getArrowscanseeimg() + "\"/></td></tr>\n"); }
		 */
		/*
		 * emailTemplate.append("<tr><td></td></tr>");
		 * emailTemplate.append("<tr><td></td></tr>");
		 */
		emailTemplate.append("<table border=\"0\">");
		emailTemplate.append("<tr><td> more information at <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a></td></tr>");
		emailTemplate.append("</table>");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}
	/**
	 * This method for sharing hotdeal information through mail.
	 * 
	 * @param hdDetailslist
	 *            contains hot deal information
	 * @return response
	 */
	public static String formHotdealInfoHTML(List<HotDealsDetails> hdDetailslist) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formHotdealInfoHTML ");
		// To format date
		for (HotDealsDetails hdDetails : hdDetailslist) {
			hdDetails.setIsDateFormated(false);
			hdDetails.sethDStartDate(hdDetails.gethDStartDate());
			hdDetails.sethDEndDate(hdDetails.gethDEndDate());
			hdDetails.setIsDateFormated(null);
		}

		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body> <h4> " + hdDetailslist.get(0).getShareText() + " </h4>\n");
		emailTemplate.append("<table border=\"0\">");
		emailTemplate.append("<tr>"); // <td width=\"300\" rowspan=\"7\">");

		/*
		 * if ("" !=
		 * Utility.checkNull(hdDetailslist.get(0).getHotDealImagePath()) &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hdDetailslist.get(0).getHotDealImagePath())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * hdDetailslist.get(0).getHotDealImagePath() + "\"/>"); }
		 * emailTemplate.append("</td>");
		 */
		// To remove CDATA in hot deal name
		String strHotDealName = hdDetailslist.get(0).getHotDealName();
		if (strHotDealName.contains("<![CDATA[")) {
			strHotDealName = strHotDealName.substring(9);
			strHotDealName = strHotDealName.substring(0, strHotDealName.length() - 3);
		}

		emailTemplate.append("<td height=\"36\"><b>HotDeal Name:</b> " + strHotDealName + "</td></tr>");
		if (hdDetailslist.get(0).getQrUrl() != null && !hdDetailslist.get(0).getQrUrl().equals("N/A")) {
			emailTemplate.append("<tr><td  height=\"36\"><b>HotDeal URL:</b> <a href=\"" + Utility.getTinyURL(hdDetailslist.get(0).getQrUrl()) + "\">"
					+ Utility.getTinyURL(hdDetailslist.get(0).getHdURL()) + "</a></td></tr>");
		}

		/*
		 * emailTemplate.append("<tr><td  height=\"36\"><b>HotDeal Start Date:</b> "
		 * + hotDealsDetailslst.get(0).gethDStartDate() + "</td></tr>"); if
		 * (hotDealsDetailslst.get(0).gethDEndDate() != null) {
		 * emailTemplate.append
		 * ("<tr><td  height=\"36\"><b>HotDeal End Date:</b> " +
		 * hotDealsDetailslst.get(0).gethDEndDate() + "</td></tr>"); }
		 * emailTemplate.append("<tr><td></td></tr>\n"); if
		 * (hotDealsDetailslst.get(0).getScanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getScanseeimg())) {
		 * emailTemplate
		 * .append("<tr><td><img height=\"40\" width=\"150\" src=\"" +
		 * hotDealsDetailslst.get(0).getScanseeimg() + "\"/></td></tr>\n"); } if
		 * (hotDealsDetailslst.get(0).getFacebookimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getFacebookimg())) {
		 * emailTemplate.append("<tr><td><img height=\"50\" width=\"50\" src=\""
		 * + hotDealsDetailslst.get(0).getFacebookimg() + "\"/>\n"); } if
		 * (hotDealsDetailslst.get(0).getTwitterimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getTwitterimg())) {
		 * emailTemplate.append("<img height=\"50\" width=\"50\" src=\"" +
		 * hotDealsDetailslst.get(0).getTwitterimg() + "\"/>"); } if
		 * (hotDealsDetailslst.get(0).getArrowscanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getArrowscanseeimg
		 * ())) { emailTemplate.append("<img height=\"52\" width=\"52\" src=\""
		 * + hotDealsDetailslst.get(0).getArrowscanseeimg() +
		 * "\"/></td></tr>\n"); }
		 */

		emailTemplate.append("<tr><td></td></tr>");
		emailTemplate.append("<tr><td></td></tr>");
		emailTemplate.append("</table>");

		emailTemplate.append("<h4> more information at <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a></h4>");

		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	/**
	 * This method for sharing hotdeal information through mail.
	 * 
	 * @param hdDetailslist
	 *            contains hot deal information
	 * @return response
	 */
	public static String formHotdealInfoHTML_ANDROID(List<HotDealsDetails> hdDetailslist) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formHotdealInfoHTML ");
		// To format date
		for (HotDealsDetails hdDetails : hdDetailslist) {
			hdDetails.setIsDateFormated(false);
			hdDetails.sethDStartDate(hdDetails.gethDStartDate());
			hdDetails.sethDEndDate(hdDetails.gethDEndDate());
			hdDetails.setIsDateFormated(null);
		}

		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body> <h4> " + hdDetailslist.get(0).getShareText() + " </h4>\n");
		/* emailTemplate.append("<table border=\"0\">"); */
		/*
		 * emailTemplate.append("<tr>"); //<td width=\"300\" rowspan=\"7\">");
		 */
		/*
		 * if ("" !=
		 * Utility.checkNull(hdDetailslist.get(0).getHotDealImagePath()) &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hdDetailslist.get(0).getHotDealImagePath())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * hdDetailslist.get(0).getHotDealImagePath() + "\"/>"); }
		 * emailTemplate.append("</td>");
		 */
		// To remove CDATA in hot deal name
		String strHotDealName = hdDetailslist.get(0).getHotDealName();
		if (strHotDealName.contains("<![CDATA[")) {
			strHotDealName = strHotDealName.substring(9);
			strHotDealName = strHotDealName.substring(0, strHotDealName.length() - 3);
			emailTemplate.append("<p><b>HotDeal Name:</b> " + strHotDealName + "</p>");
		}

		if (hdDetailslist.get(0).getQrUrl() != null && !hdDetailslist.get(0).getQrUrl().equals("N/A")) {
			emailTemplate.append("<p><b>HotDeal URL:</b> <a href=\"" + Utility.getTinyURL(hdDetailslist.get(0).getQrUrl()) + "\">"
					+ Utility.getTinyURL(hdDetailslist.get(0).getHdURL()) + "</a></p>");
		}

		/*
		 * emailTemplate.append("<tr><td  height=\"36\"><b>HotDeal Start Date:</b> "
		 * + hotDealsDetailslst.get(0).gethDStartDate() + "</td></tr>"); if
		 * (hotDealsDetailslst.get(0).gethDEndDate() != null) {
		 * emailTemplate.append
		 * ("<tr><td  height=\"36\"><b>HotDeal End Date:</b> " +
		 * hotDealsDetailslst.get(0).gethDEndDate() + "</td></tr>"); }
		 * emailTemplate.append("<tr><td></td></tr>\n"); if
		 * (hotDealsDetailslst.get(0).getScanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getScanseeimg())) {
		 * emailTemplate
		 * .append("<tr><td><img height=\"40\" width=\"150\" src=\"" +
		 * hotDealsDetailslst.get(0).getScanseeimg() + "\"/></td></tr>\n"); } if
		 * (hotDealsDetailslst.get(0).getFacebookimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getFacebookimg())) {
		 * emailTemplate.append("<tr><td><img height=\"50\" width=\"50\" src=\""
		 * + hotDealsDetailslst.get(0).getFacebookimg() + "\"/>\n"); } if
		 * (hotDealsDetailslst.get(0).getTwitterimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getTwitterimg())) {
		 * emailTemplate.append("<img height=\"50\" width=\"50\" src=\"" +
		 * hotDealsDetailslst.get(0).getTwitterimg() + "\"/>"); } if
		 * (hotDealsDetailslst.get(0).getArrowscanseeimg() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(hotDealsDetailslst.get(0).getArrowscanseeimg
		 * ())) { emailTemplate.append("<img height=\"52\" width=\"52\" src=\""
		 * + hotDealsDetailslst.get(0).getArrowscanseeimg() +
		 * "\"/></td></tr>\n"); }
		 */

		/*
		 * emailTemplate.append("<tr><td></td></tr>");
		 * emailTemplate.append("<tr><td></td></tr>");
		 * emailTemplate.append("</table>");
		 */
		emailTemplate.append("<p></p>");

		emailTemplate.append("<p> more information at <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a></p>");

		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}
	/**
	 * The method for forming HTML with retailer Info.
	 * 
	 * @param productDetail
	 *            product object.
	 * @param retailerDetail
	 *            retailer object
	 * @param userId
	 *            int parameter
	 * @return The email template.
	 * @throws NoSuchAlgorithmException
	 *             - Exception related to algorithm
	 * @throws NoSuchPaddingException
	 *             - Exception related to Padding
	 * @throws InvalidKeyException
	 *             - Exception related to InvalidKey
	 * @throws InvalidAlgorithmParameterException
	 *             - Exception related to InvalidAlgorithmParameter
	 * @throws InvalidKeySpecException
	 *             - Exception related to InvalidKeySpec
	 * @throws IllegalBlockSizeException
	 *             - Exception related to IllegalBlockSize
	 * @throws BadPaddingException
	 *             - Exception related to BadPaddings
	 */

	public static String formShareAppInfoHTML(List<RetailersDetails> arRetailersDetailsList) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {
		LOG.info("Inside Utility : formShareAppInfoHTML ");
		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body style='font-family:aerial;font-size:12px'> <h4> " + arRetailersDetailsList.get(0).getShareText() + "</h4>\n");
		emailTemplate.append("<table border=\"0\">");
		/*
		 * emailTemplate.append("<tr><td width=\"300\" rowspan=\"7\">");
		 * 
		 * if (arRetailersDetailsList.get(0).getRetImage() != null &&
		 * !HubCitiConstants
		 * .NOTAPPLICABLE.equals(arRetailersDetailsList.get(0).getRetImage())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * arRetailersDetailsList.get(0).getRetImage() + "\"/></tr>"); }
		 */

		if (null != arRetailersDetailsList.get(0).getQrUrl() && !"N/A".equals(arRetailersDetailsList.get(0).getQrUrl())) {
			emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Visit:</b> <a href=\""+Utility.getTinyURL(arRetailersDetailsList.get(0).getQrUrl()) +"\">" + Utility.getTinyURL(arRetailersDetailsList.get(0).getQrUrl()) + "</a></td></tr>");
		}
		emailTemplate.append("</table>");

		emailTemplate.append("<h4>Check out  <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a> for more.</h4>\n");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	/**
	 * This method for sharing special offer information through mail.
	 * 
	 * @param specialOfflst
	 *            contains RetailersDetails information
	 * @return response
	 */
	public static String formSpecailOffInfoHtml(List<RetailersDetails> specialOfflst) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {
		LOG.info("Inside Utility : formSpecailOffInfoHtml ");

		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body> <h4> " + specialOfflst.get(0).getShareText() + "</h4>\n");
		emailTemplate.append("<table border=\"0\">");

		/*
		 * emailTemplate.append("<tr><td width=\"300\" rowspan=\"7\">");
		 * 
		 * if (specialOfflst.get(0).getRetImage() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE
		 * .equals(specialOfflst.get(0).getRetImage())) { if
		 * ("".equals(Utility.checkNull(specialOfflst.get(0).getAppIcon()))) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * specialOfflst.get(0).getRetImage() + "\"/></tr>"); //
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * specialOfflst.get(0).getAppIcon() + "\"/></tr>"); }
		 */

		if (null != specialOfflst.get(0).getQrUrl() && !"N/A".equals(specialOfflst.get(0).getQrUrl())) {
			emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Visit:</b> " + Utility.getTinyURL(specialOfflst.get(0).getQrUrl()) + "</td></tr>");
		}
		/* emailTemplate.append("</table>"); */

		emailTemplate.append("<tr><td></td></tr>\n");
		emailTemplate.append("</table>");
		emailTemplate.append("<p>more information at <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a></p>");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");

		return emailTemplate.toString();
	}

	public static String formShareDownLoadLinkHTML(UserDetails shareInfo) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {
		LOG.info("Inside Utility : formShareDownLoadLinkHTML ");
		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");

		emailTemplate.append("<body style='font-family: Arial,Helvetica,sans-serif;'> ");
		emailTemplate.append("<p>Hi,</p>\n");
		emailTemplate.append("<h5> " + HubCitiConstants.SHAREDOWNLOADTEXT + "</h5>\n");

		emailTemplate.append("<table border=\"0\">\n");

		emailTemplate
				.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;color:#137EBD'><td width=\"10\"><img height=\"26\" width=\"26\" title=\"iTunes\" src=\""
						+ shareInfo.getiTunesImg() + "\"/></td><td>" + shareInfo.getiTunesURL() + "</td></tr>\n");

		emailTemplate.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;'><td width=\"10\"><img height=\"26\" width=\"26\" title=\"Play Store\" src=\""
				+ shareInfo.getAndroidImg() + "\"/></td><td>" + shareInfo.getGooglePlayURL() + "</td></tr>\n");

		emailTemplate.append("<tr><td colspan=\"2\">&nbsp;</td></tr>");
		emailTemplate.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;'><td>\n");
		emailTemplate.append("Thank you, </td></tr>\n");

		emailTemplate.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;'><td>");
		emailTemplate.append("HubCiti Team</td></tr>\n");
		emailTemplate.append("</table>");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	/**
	 * Implementation for Android specific changes
	 * 
	 * @param shareInfo
	 * @return
	 * @throws NoSuchAlgorithmException
	 * @throws NoSuchPaddingException
	 * @throws InvalidKeyException
	 * @throws InvalidAlgorithmParameterException
	 * @throws InvalidKeySpecException
	 * @throws IllegalBlockSizeException
	 * @throws BadPaddingException
	 */
	public static String formShareDownLoadLinkHTML_WithoutImTag(UserDetails shareInfo) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {
		LOG.info("Inside Utility : formShareDownLoadLinkHTML ");
		final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");

		emailTemplate.append("<body style='font-family: Arial,Helvetica,sans-serif;'> ");
		emailTemplate.append("<p>Hi,</p>\n");
		emailTemplate.append("<h5> " + HubCitiConstants.SHAREDOWNLOADTEXT + "</h5>\n");

		emailTemplate.append("<table border=\"0\">\n");

		emailTemplate.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;color:#137EBD'>" + /*
																													 * "<td width=\"10\"><img height=\"26\" width=\"26\" title=\"iTunes\" src=\""
																													 * +
																													 * shareInfo
																													 * .
																													 * getiTunesImg
																													 * (
																													 * )
																													 * +
																													 * "\"/></td>"
																													 */"<td>" + shareInfo.getiTunesURL() + "</td></tr><br/><br/>");

		emailTemplate.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;'>" + /*
																									 * <
																									 * td
																									 * width
																									 * =
																									 * \
																									 * "10\"><img height=\"26\" width=\"26\" title=\"Play Store\" src=\""
																									 * +
																									 * shareInfo
																									 * .
																									 * getAndroidImg
																									 * (
																									 * )
																									 * +
																									 * "\"/></td>"
																									 */"<td>" + shareInfo.getGooglePlayURL() + "</td></tr><br/>");

		emailTemplate.append("<tr><td colspan=\"2\">&nbsp;</td></tr>");
		emailTemplate.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;'><td><br/>");
		emailTemplate.append("Thank you, </td></tr><br/>");

		emailTemplate.append("<tr style='font-family: Arial,Helvetica,sans-serif;font-size:12px;'><td>");
		emailTemplate.append("HubCiti Team</td></tr>\n");
		emailTemplate.append("</table>");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}
	/**
	 * Validate Email Id with regular expression
	 * 
	 * @param strEmailId
	 *            strEmailId for validation
	 * @return true valid strEmailId, false invalid strEmailId
	 */
	public static boolean validateEmailId(final String strEmailId) {
		Pattern pattern = null;
		Matcher matcher;
		final String EMAIL_PATTERN = HubCitiConstants.EMAIL_PATTERN;
		pattern = Pattern.compile(EMAIL_PATTERN);
		matcher = pattern.matcher(strEmailId);
		return matcher.matches();
	}

	public static String formatPriceToUSLocale(String price) {
		if ("".equals(Utility.checkNull(price))) {
			price = "0";
		}
		Locale local = new Locale("en", "US");
		// double d = Double.parseDouble(price);
		NumberFormat current = NumberFormat.getCurrencyInstance(local);
		return current.format(price);
	}

	public static String removeSpecialForWebView(String inPutXml) {
		String outPutxML = "";
		if (null != inPutXml) {
			outPutxML = outPutxML.replaceAll("\n", "<br>");
			outPutxML = outPutxML.replaceAll("\r", "<br>");
		}
		return outPutxML;
	}

	public static String formShareEventInfoHTML(EventDetails eventDetails) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formShareEventInfoHTML ");
		String shortDesc = eventDetails.getShortDes().replace("<![CDATA[", "").replace("]]>", "");

		String startDate = convertDBdate(eventDetails.getStartDate());
		String endDate = "N/A";
		if (null != eventDetails.getEndDate() && !"".equals(eventDetails.getEndDate())) {
			endDate = convertDBdate(eventDetails.getEndDate());
		}
		StringBuffer emailTemplate = null;
		emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body style='font-family:aerial;font-size:12px'> <h4> " + eventDetails.getShareText() + "</h4>\n");
		emailTemplate.append("<table border=\"0\">");
		/*
		 * emailTemplate.append("<tr><td width=\"300\" rowspan=\"7\">");
		 * 
		 * if (eventDetails.getImgPath() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE.equals(eventDetails.getImgPath())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * eventDetails.getImgPath() + "\"/></tr>"); }
		 */
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Event Name:</b> " + eventDetails.getEventName() + "</td></tr>");
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Description:</b> " + shortDesc + "</td></tr>");
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Start Date:</b> " + startDate + "</td></tr>");

		if (null != endDate && !"N/A".equals(endDate)) {
			emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>End Date:</b> " + endDate + "</td></tr>");
		}

		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Visit:</b> <a href =\"" + eventDetails.getQrUrl()+"\">"+ eventDetails.getQrUrl() + "</a></td></tr>");
		emailTemplate.append("</table>");

		emailTemplate.append("<h4>Check out  <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a> for more.</h4>\n");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();

	}

	public static String formShareEventInfoHTML_ANDROID(EventDetails eventDetails) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formShareEventInfoHTML ");
		String shortDesc = eventDetails.getShortDes().replace("<![CDATA[", "").replace("]]>", "");

		String startDate = convertDBdate(eventDetails.getStartDate());
		String endDate = "N/A";
		if (null != eventDetails.getEndDate() && !"".equals(eventDetails.getEndDate())) {
			endDate = convertDBdate(eventDetails.getEndDate());
		}
		StringBuffer emailTemplate = null;
		emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body style='font-family:aerial;font-size:12px'> <h4> " + eventDetails.getShareText() + "</h4>\n");
		emailTemplate.append("<p><b>Event Name:</b> " + eventDetails.getEventName() + "</p>");
		emailTemplate.append("<p><b>Description:</b> " + shortDesc + "</p>");
		emailTemplate.append("<p><b>Start Date:</b> " + startDate + "</p>");

		if (null != endDate && !"N/A".equals(endDate)) {
			emailTemplate.append("<p><b>End Date:</b> " + endDate + "</p>");
		}

		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Visit:</b> <a href =\"" + eventDetails.getQrUrl()+"\">"+ eventDetails.getQrUrl() + "</a></td></tr>");
		emailTemplate.append("<p>Check out  <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a> for more.</p>\n");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();

	}

	/*
	 * public static String formShareEventInfoHTML(EventDetails eventDetails)
	 * throws NoSuchAlgorithmException, NoSuchPaddingException,
	 * InvalidKeyException, InvalidAlgorithmParameterException,
	 * InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {
	 * 
	 * LOG.info("Inside Utility : formShareEventInfoHTML "); String shortDesc =
	 * eventDetails.getShortDes().replace("<![CDATA[", "").replace("]]>", "");
	 * 
	 * String startDate = convertDBdate(eventDetails.getStartDate()); String
	 * endDate = eventDetails.getEndDate(); if(null != eventDetails.getEndDate()
	 * && !"".equals(eventDetails.getEndDate()) &&
	 * !eventDetails.getEndDate().equals(HubCitiConstants.NOTAPPLICABLE)) {
	 * endDate = convertDBdate(eventDetails.getEndDate());
	 * 
	 * }
	 * 
	 * 
	 * emailTemplate.append(
	 * "<tr><td width=\"300\" height=\"36\"><b>Event Name:</b> " +
	 * eventDetails.getEventName() + "</td></tr>"); emailTemplate.append(
	 * "<tr><td width=\"300\" height=\"36\"><b>Description:</b> " + shortDesc +
	 * "</td></tr>"); emailTemplate.append(
	 * "<tr><td width=\"300\" height=\"36\"><b>Start Date:</b> " + startDate +
	 * "</td></tr>");
	 * emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>End Date:</b> "
	 * + endDate + "</td></tr>");
	 * emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Visit:</b> "
	 * + eventDetails.getQrUrl() + "</td></tr>");
	 * emailTemplate.append("</table>");
	 * 
	 * emailTemplate.append(
	 * "<h4>Check out  <a href=\"HubCitiapp.com\">hubcitiapp.com</a> for more.</h4>\n"
	 * ); emailTemplate.append("</body>"); emailTemplate.append("</html>\n");
	 * return emailTemplate.toString(); }
	 */

	public static String getTinyURL(String url) {
		String tinyUrl = HubCitiConstants.TINYAPIURL;
		String tinyUrlLookup = tinyUrl + url;
		BufferedReader reader;
		String strShorturl = null;
		try {
			reader = new BufferedReader(new InputStreamReader(new URL(tinyUrlLookup).openStream()));
			strShorturl = reader.readLine();
		} catch (MalformedURLException e) {
			LOG.error("Error occureed in getTinyURL", e.getMessage());
		} catch (IOException e) {
			LOG.error("Error occureed in getTinyURL", e.getMessage());
		}
		return strShorturl;
	}

	public static String formShareFundraiserInfoHTML(Fundraiser fundraiser) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formShareFundraiserInfoHTML ");
		String shortDesc = fundraiser.getsDescription().replace("<![CDATA[", "").replace("]]>", "");

		StringBuffer emailTemplate = null;
		emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body style='font-family:aerial;font-size:12px'> <h4> " + fundraiser.getShareText() + "</h4>\n");
		emailTemplate.append("<table border=\"0\">");
		/*
		 * emailTemplate.append("<tr><td width=\"300\" rowspan=\"7\">");
		 * 
		 * if (fundraiser.getImgPath() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE.equals(fundraiser.getImgPath())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * fundraiser.getImgPath() + "\"/>"); } emailTemplate.append("</td>");
		 */
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Fundraiser Name:</b> " + fundraiser.getFundName() + "</td></tr>");
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Description:</b> " + shortDesc + "</td></tr>");
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Start Date:</b> " + fundraiser.getsDate() + "</td></tr>");

		if (null != fundraiser.geteDate() && !"N/A".equals(fundraiser.geteDate())) {
			emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>End Date:</b> " + fundraiser.geteDate() + "</td></tr>");
		}
		emailTemplate.append("<tr><td width=\"300\" height=\"36\"><b>Visit:</b> " + fundraiser.getQrUrl() + "</td></tr>");
		emailTemplate.append("</table>");

		emailTemplate.append("<h4>Check out  <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a> for more.</h4>\n");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	public static String formShareFundraiserInfoHTML_ANDROID(Fundraiser fundraiser) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
			InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {

		LOG.info("Inside Utility : formShareFundraiserInfoHTML ");
		String shortDesc = fundraiser.getsDescription().replace("<![CDATA[", "").replace("]]>", "");

		StringBuffer emailTemplate = null;
		emailTemplate = new StringBuffer("<html><head></head>");
		emailTemplate.append("<body style='font-family:aerial;font-size:12px'> <h4> " + fundraiser.getShareText() + "</h4>\n");
		/* emailTemplate.append("<table border=\"0\">"); */
		/*
		 * emailTemplate.append("<tr><td width=\"300\" rowspan=\"7\">");
		 * 
		 * if (fundraiser.getImgPath() != null &&
		 * !HubCitiConstants.NOTAPPLICABLE.equals(fundraiser.getImgPath())) {
		 * emailTemplate.append("<img height=\"250\" width=\"250\" src=\"" +
		 * fundraiser.getImgPath() + "\"/>"); } emailTemplate.append("</td>");
		 */
		emailTemplate.append("<p><b>Fundraiser Name:</b> " + fundraiser.getFundName() + "</p>");
		emailTemplate.append("<p><h4><b>Description:</b> " + shortDesc + "</h4></p>");
		emailTemplate.append("<p><b>Start Date:</b> " + fundraiser.getsDate() + "</p>");

		if (null != fundraiser.geteDate() && !"N/A".equals(fundraiser.geteDate())) {
			emailTemplate.append("<p><b>End Date:</b> " + fundraiser.geteDate() + "</p>");
		}
		emailTemplate.append("<p><b>Visit:</b> " + fundraiser.getQrUrl() + "</p>");
		/* emailTemplate.append("</table>"); */

		emailTemplate.append("<p>Check out  <a href=\"http://www.hubcitiapp.com\">http://www.hubcitiapp.com</a> for more.</p>\n");
		emailTemplate.append("</body>");
		emailTemplate.append("</html>\n");
		return emailTemplate.toString();
	}

	/*
	 * public static String getTinyURL(String url) { String tinyUrl =
	 * HubCitiConstants.TINYAPIURL; String tinyUrlLookup = tinyUrl + url;
	 * BufferedReader reader; String strShorturl = null; try { reader = new
	 * BufferedReader(new InputStreamReader(new
	 * URL(tinyUrlLookup).openStream())); strShorturl = reader.readLine(); }
	 * catch (MalformedURLException e) {
	 * LOG.error("Error occureed in getTinyURL", e.getMessage()); } catch
	 * (IOException e) { LOG.error("Error occureed in getTinyURL",
	 * e.getMessage()); } return strShorturl; }
	 */

	/**
	 * Method to check for is string contains characters which is illegal in XML
	 * for parsing.
	 * 
	 * @param data
	 * @return
	 */
	public static final Boolean checkXMLIllegalCharacter(String data) {

		Boolean flag = false;
		if (null != data && !"".equals(data)) {
			if (data.contains("é")) {
				data = data.replaceAll("é", "&#235;");
			}
			for (int i = 0; i < XML_ILLEGAL_CHAR.length; i++) {
				if (data.contains(XML_ILLEGAL_CHAR[i])) {
					flag = true;
					break;
				}
			}
		}
		return flag;
	}

	/**
	 * The method to get the current date formated in yyyy-MM-dd HH:mm:ss
	 * format.
	 * 
	 * @param dbdate
	 *            -As parameter
	 * @return The current date formatted in yyyy-MM-dd HH:mm:ss forma
	 */

	public static String convertHDealDBdate(String dbdate) {
		String javaDate = null;
		try {
			SimpleDateFormat formatter, FORMATTER;
			// formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
			formatter = new SimpleDateFormat("yyyy-MM-dd");
			Date date = formatter.parse(dbdate);
			FORMATTER = new SimpleDateFormat("MMMM dd, yyyy");
			// LOG.info("NewDate-->" + FORMATTER.format(date));
			javaDate = FORMATTER.format(date);
		} catch (ParseException exception) {
			LOG.error("Inside Utility : convertHDealDBdate " + exception.getMessage());
			return null;
		}
		return javaDate;
	}

	public static String clobToString(java.sql.Clob data) {
		final StringBuilder sb = new StringBuilder();
		try {
			if (null == data) {
				return null;
			}

			final Reader reader = data.getCharacterStream();
			final BufferedReader br = new BufferedReader(reader);

			int b;
			while (-1 != (b = br.read())) {
				sb.append((char) b);
			}
			br.close();
		} catch (SQLException e) {
			LOG.error("Inside Utility : convertHDealDBdate " + e.getMessage());
			return e.toString();
		} catch (IOException e) {
			LOG.error("Inside Utility : convertHDealDBdate " + e.getMessage());
			return e.toString();
		}
		return sb.toString();
	}

	public static String formResponseJSON(String userInvalidcode, String text) {

		StringBuffer buffer = new StringBuffer();

		buffer.append("{");
		buffer.append("\"response\":");
		buffer.append("{");
		buffer.append("\"responseCode\"");
		buffer.append(":");
		buffer.append("\"");
		buffer.append(userInvalidcode);
		buffer.append("\"");
		buffer.append(",");
		buffer.append("\"responseText\"");
		buffer.append(":");
		buffer.append("\"");
		buffer.append(text);
		buffer.append("\"");
		buffer.append("}");
		buffer.append("}");
		return buffer.toString();

	}

	public static String validationResponseJSON(String errorCode, String errorResponse) {
		final StringBuilder response = new StringBuilder();
		response.append("{");
		response.append("\"response\": {");
		response.append("\"responseCode\":");
		response.append("\"" + errorCode + "\"");
		response.append(",\"responseText\":");
		response.append("\"" + errorResponse + "\"");
		response.append("}}");
		return response.toString();
	}

	public static String validRespJSON(String errorCode, String errorResponse) {
		final StringBuilder response = new StringBuilder();
		response.append("{");
		response.append("\"responseCode\":");
		response.append("\"" + errorCode + "\"");
		response.append(",\"responseText\":");
		response.append("\"" + errorResponse + "\"");
		response.append("}");
		return response.toString();
	}

	/**
	 * this method returns the xml String for the given Values.
	 * 
	 * @param errorCode
	 *            The error code.
	 * @param errorResponse
	 *            The error response.
	 * @return response with formed response.
	 */
	public static String validationResponseJSON(String errorCode, String errorResponse, String paramNode3, String paramValue3) {
		final StringBuilder response = new StringBuilder();

		response.append("{");
		response.append("\"responseCode\":");
		response.append("\"" + errorCode + "\"");
		response.append(",\"responseText\":");
		response.append("\"" + errorResponse + "\"");
		response.append(",\"" + paramNode3 + "\":");
		response.append("\"" + paramValue3 + "\"");
		response.append("}");
		return response.toString();
	}

	
	/**
	 * this method returns the xml String for the given Values.
	 * 
	 * @param errorCode
	 *            The error code.
	 * @param errorResponse
	 *            The error response.
	 * @return response with formed response.
	 */
	public static String validationResponseJSON(String errorCode, String errorResponse, String paramNode3, String paramValue3,String paramNode4,String paramValue4) {
		final StringBuilder response = new StringBuilder();

		response.append("{");
		response.append("\"responseCode\":");
		response.append("\"" + errorCode + "\"");
		response.append(",\"responseText\":");
		response.append("\"" + errorResponse + "\"");
		response.append(",\"" + paramNode3 + "\":");
		response.append("\"" + paramValue3 + "\"");
		response.append(",\"" + paramNode4 + "\":");
		response.append("\"" + paramValue4 + "\"");
		response.append("}");
		return response.toString();
	}
	/**
	 * this method returns the xml String for the given Values.
	 * 
	 * @param errorCode
	 *            The error code.
	 * @param errorResponse
	 *            The error response.
	 * @return response with formed response.
	 */
	public static String addJSONResponse(String successCode, String successResponse, String subLevelResponse) {

		final StringBuilder response = new StringBuilder();
		response.append("{");
		response.append("\"responseCode\":");
		response.append("\"" + successCode + "\"");
		response.append(",\"responseText\":");
		response.append("\"" + successResponse + "\"");
		response.append(subLevelResponse);
		// response.append("}");

		return response.toString();
	}

	/**
	 * The method to change gova date format from (2015-09-24T12:36:00-05:00 to
	 * 09/29/2015).
	 * 
	 * @param string
	 *            containing date.
	 * @return formated date as string.
	 */
	public static String govQADateFormat(String strGovaDate) {

		final int iEndCnt = Integer.parseInt(PropertiesReader.getPropertyValue(HubCitiConstants.DATE_LENGTH).toString());
		String formattedDate = null;
		SimpleDateFormat strDateFmt = null;

		if (!"".equals(Utility.checkNull(strGovaDate))) {
			strGovaDate = strGovaDate.substring(0, strGovaDate.length() - iEndCnt);
			try {

				SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
				Date date = sdf.parse(strGovaDate);
				strDateFmt = new SimpleDateFormat("MM/dd/yyyy");
				formattedDate = strDateFmt.format(date);
			} catch (ParseException exception) {
				LOG.info("Inside Utility : govQADateFormat " + exception.getMessage());
				return null;
			}
		}
		return formattedDate;
	}

	/**
	 * The method to transforms String XML into Java Object by using DOM.
	 * 
	 * @param String
	 *            XML.
	 * @return table object.
	 */
	public static Table DOMParseToObject(String xmlString) {

		Table objTable = new Table();
		DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		try {
			DocumentBuilder builder = factory.newDocumentBuilder();
			Document doc = builder.parse(new InputSource(new StringReader(xmlString)));
			Element element = doc.getDocumentElement();
			NodeList nodes = element.getChildNodes();

			Table objFields = null;

			List<Table> table = new ArrayList<Table>();

			for (int i = 0; i < nodes.getLength(); i++) {

				if ("reference_no".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setReferNum(nodes.item(i).getTextContent());
				} else if ("request_description".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setDescription(nodes.item(i).getTextContent());
				} else if ("service_request_status_id".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setStatusId(nodes.item(i).getTextContent());
				} else if ("status_description".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setStatusDesc(nodes.item(i).getTextContent());
				} else if ("contact_email".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setEmail(nodes.item(i).getTextContent());
				} else if ("issue_id".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setIssueId(nodes.item(i).getTextContent());
				} else if ("department_name".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setDeptName(nodes.item(i).getTextContent());
				} else if ("create_date".equals(nodes.item(i).getNodeName().toLowerCase())) {
					objTable.setCreateDate(nodes.item(i).getTextContent());
				} else {
					if (nodes.item(i).getNodeName().contains(HubCitiConstants.HEXIDECIMAL)) {
						objFields = new Table();
						objFields.setFldName(removeSpecialChar(nodes.item(i).getNodeName()));
						objFields.setFldValue(nodes.item(i).getTextContent());
						table.add(objFields);
						objTable.setTable(table);
					}
				}
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return objTable;
	}

	/**
	 * The method to handle special character.
	 * 
	 * @param String
	 *            XML.
	 * @return table object.
	 */
	public static String removeSpecialChar(String strLabel) {
		String strOutput = "";
		if (null != strLabel) {
			strOutput = null;
			strOutput = strLabel.replaceAll("_x0020_", " ");
			strOutput = strOutput.replaceAll("_x003A_", " : ");
			strOutput = strOutput.replaceAll("_x002A_", "*");
			strOutput = strOutput.replaceAll("_x003F_", "?");
			strOutput = strOutput.replaceAll("_x002f _", "/");
		}
		return strOutput;
	}

	/**
	 * The method to handle Standard Formatters"2015-11-02T12:53:32.429".
	 * 
	 * 
	 * @return JODA date (2015-11-02T12:53:32.429).
	 */
	public static String ISODateTimeFormat() {
		String strJodaDate = null;
		final Date date = new Date();
		final SimpleDateFormat strFormatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS", Locale.US);
		strJodaDate = strFormatter.format(date);
		return strJodaDate;
	}

	/**
	 * getFormattedDate method will convert date format to MM/dd/yyyy.
	 * 
	 * @param enteredDate
	 *            As input parameter
	 * @return converted date.
	 * @throws java.text.ParseException
	 *             Exception while parsing date.
	 */

	public static String formattedDate(String enteredDate) {
		String strDBDate = null;

		try {
			DateFormat oldFormatter = new SimpleDateFormat("yyyy-MM-dd");
			DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");

			Date convertedDate = (Date) oldFormatter.parse(enteredDate);
			strDBDate = formatter.format(convertedDate);

		} catch (ParseException exception) {
			LOG.info("Inside Utility : formattedDate " + exception.getMessage());
			return null;
		}
		return strDBDate;
	}

	public static String generateErrRespJSON(String errorCode, String errorResponse) {
		final StringBuilder response = new StringBuilder();
		response.append("{");
		response.append("\"responseCode\":");
		response.append("\"" + errorCode + "\"");
		response.append(",\"responseText\":");
		response.append("\"" + errorResponse + "\"");
		response.append("}");
		return response.toString();
	}

	/**
	 * The method to transforms String XML into Java Object by using DOM.
	 * 
	 * @param String
	 *            XML.
	 * @return table object.
	 */
	public static Integer DOMParseToFindCategory(String xmlString) {

		DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		Integer iGpsEnabled = 0;
		try {
			DocumentBuilder builder = factory.newDocumentBuilder();
			Document doc = builder.parse(new InputSource(new StringReader(xmlString)));
			Element element = doc.getDocumentElement();
			NodeList nodes = element.getChildNodes();

			for (int i = 0; i < nodes.getLength(); i++) {

				if ("gpsEnabled".equals(nodes.item(i).getNodeName())) {
					iGpsEnabled = Integer.parseInt(nodes.item(i).getTextContent());
				}
			}

		} catch (Exception ex) {
			LOG.info("Inside Utility : DOMParseToFindCategory " + ex.getMessage());
		}

		return iGpsEnabled;
	}

	/**
	 * This method return phone number in (123)456-7890.
	 * 
	 * @param strPhoneNo
	 * @return
	 */
	public static String getPhoneFormate(String strPhoneNo) {
		StringBuilder strPhoneNum = null;
		strPhoneNum = new StringBuilder(strPhoneNo).insert(0, "(").insert(4, ")").insert(8, "-");
		return strPhoneNum.toString();
	}

	// used for generating auto generator password
	public static String randomString(int len) {
		Random rnd = new Random();
		StringBuilder sb = new StringBuilder(len);
		for (int i = 0; i < len; i++)
			sb.append(autoGeneratedPswd.charAt(rnd.nextInt(autoGeneratedPswd.length())));
		return sb.toString();
	}
	
	
	public static Date bandDateFormat(String dateString){
		
		DateFormat format = new SimpleDateFormat("MM-dd-yyyy", Locale.ENGLISH);
		Date date = null;
		
		try {
		
			date = format.parse(dateString);
		
		} catch (ParseException e) {
			LOG.info("Unabkle to Convert Date Format" + dateString);
		}
		
		return date;
	}
	
	
	public static String convertmmFormattoMMMFormat(String inputDate){
		
		String outputDate = null;
		
		DateFormat formatInput = new SimpleDateFormat("MM-dd-yyyy", Locale.ENGLISH);
		
		DateFormat formatOutput = new SimpleDateFormat("MMM dd, yyyy", Locale.ENGLISH);
		
		Date date = null;
		
		try {
			date  = formatInput.parse(inputDate);
			outputDate = formatOutput.format(date);
		} catch (ParseException e) {
			LOG.info("Unable to Parse Date : convertmmFormattoMMMFormat \t" + e.getMessage() );
			outputDate = inputDate;
		}
		return outputDate;
	}
	
	
public static String claimEmailTemplate1(CustomerInfo objCustomerInfo ) {
		LOG.info("Inside Utility : claimEmailTemplate");
		
		final StringBuffer msgBody  = new StringBuffer("<html><head></head>");
		msgBody.append("<body style='font-family:aerial;font-size:12px'> <h4> " + "Hi Team, <br> <br>&nbsp;&nbsp;Please find the below contact details who is trying to claim this location." + "</h4>\n");
		msgBody.append("<table border=\"0\">");

		//String strName, String strPhone, String strEmail, String strRetName, String strRetAddress
		
		/*msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Name: </b>" + strName +"</td></tr>");
		msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Phone Number: </b>" + strPhone +"</td></tr>");
		msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Email Address: </b>" + strEmail +"</td></tr>");
		msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Retailer Name: </b>" + strRetName +"</td></tr>");
		if (!"".equals(Utility.checkNull(strRetAddress))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Retailer Address: </b>" + strRetAddress +"</td></tr>");
		}*/
		msgBody.append("</table>");

		msgBody.append("<h4>Regards,<br>HubCiti Team</h4>");
		msgBody.append("</body>");
		msgBody.append("</html>\n");
		msgBody.toString();
		return msgBody.toString();
	}


public static String claimEmailTemplate(CustomerInfo objCustomerInfo,CustomerInfo objClaimDetailsDb ) {
	LOG.info("Inside Utility : claimEmailTemplate");

	final StringBuffer msgBody  = new StringBuffer("<html><head></head>");
	msgBody.append("<body style='font-family:aerial;font-size:12px'> <h4> " + "Hi Team, <br> <br>&nbsp;&nbsp;Please find the below contact details who is trying to claim this business." + "</h4>\n");
	msgBody.append("<table border=\"0\">");

	if (!"".equals(Utility.checkNull(objCustomerInfo.getName()))) {
		if(null == objClaimDetailsDb.getName() || !objCustomerInfo.getName().equals(objClaimDetailsDb.getName()))
			msgBody.append("<tr><td  height=\"36\" ><b>&nbsp;&nbsp;&nbsp;&nbsp;Business Name:  </b><span style=\"color:red\">" + objCustomerInfo.getName() +"</span></td></tr>");
		else 
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Business Name:  </b>" + objCustomerInfo.getName() +"</td></tr>");	
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getType()))) {
		if(null == objClaimDetailsDb.getType() || !objCustomerInfo.getType().equals(objClaimDetailsDb.getType()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Type of Business: </b><span style=\"color:red\">" + objCustomerInfo.getType() +"</span></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Type of Business: </b>" + objCustomerInfo.getType() +"</td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getWebsite()))) {
		if(null == objClaimDetailsDb.getWebsite() || !objCustomerInfo.getWebsite().equals(objClaimDetailsDb.getWebsite()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Website: </b><a href=\""+objCustomerInfo.getWebsite()+"\" style=\"color:red\"><span style=\"color:red\">" + objCustomerInfo.getWebsite() +"</span></a></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Website: </b>" + objCustomerInfo.getWebsite() +"</td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getKeywords()))) {
		if(null == objClaimDetailsDb.getKeywords() || !objCustomerInfo.getKeywords().equals(objClaimDetailsDb.getKeywords()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Keywords: </b><span style=\"color:red\">" + objCustomerInfo.getKeywords() +"</span></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Keywords: </b>" + objCustomerInfo.getKeywords() +"</td></tr>");
	}


	if (!"".equals(Utility.checkNull(objCustomerInfo.getRetAddress()))) {
		if(null == objClaimDetailsDb.getRetAddress() || !objCustomerInfo.getRetAddress().equals(objClaimDetailsDb.getRetAddress()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Street Address: </b><span style=\"color:red\">" + objCustomerInfo.getRetAddress() +"</span></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Street Address: </b>" + objCustomerInfo.getRetAddress() +"</td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getRetAddress2()))) {
		if(null == objClaimDetailsDb.getRetAddress2() || !objCustomerInfo.getRetAddress2().equals(objClaimDetailsDb.getRetAddress2()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Street Address line 2: </b><span style=\"color:red\">" + objCustomerInfo.getRetAddress2() +"</span></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Street Address line 2: </b>" + objCustomerInfo.getRetAddress2() +"</td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getCity()))) {
		if(null == objClaimDetailsDb.getCity() || !objCustomerInfo.getCity().equals(objClaimDetailsDb.getCity()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;City: </b><span style=\"color:red\">" + objCustomerInfo.getCity() +"</td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;City: </b>" + objCustomerInfo.getCity() +"</td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getState()))) {
		if(null == objClaimDetailsDb.getState() || !objCustomerInfo.getState().equals(objClaimDetailsDb.getState()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;State / Province: </b><span style=\"color:red\">" + objCustomerInfo.getState() +"</span></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;State / Province: </b>" + objCustomerInfo.getState() +"</td></tr>");
	}



	if (!"".equals(Utility.checkNull(objCustomerInfo.getPostalCode()))) {
		if(null == objClaimDetailsDb.getPostalCode() || !objCustomerInfo.getPostalCode().equals(objClaimDetailsDb.getPostalCode()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Postal / Zip Code: </b><span style=\"color:red\">" + objCustomerInfo.getPostalCode() +"</span></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Postal / Zip Code: </b>" + objCustomerInfo.getPostalCode() +"</td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getCountry()))) {
		if(null==objClaimDetailsDb.getCountry() || !objCustomerInfo.getCountry().equals(objClaimDetailsDb.getCountry()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Country: </b><span style=\"color:red\">" + objCustomerInfo.getCountry() +"</span></td></tr>");	
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Country: </b>" + objCustomerInfo.getCountry() +"</td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getPhone()))) {
		if(null == objClaimDetailsDb.getPhone() || !objCustomerInfo.getPhone().equals(objClaimDetailsDb.getPhone()))
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Phone: </b><span style=\"color:red\">" + objCustomerInfo.getPhone() +"</span></td></tr>");
		else
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Phone: </b>" + objCustomerInfo.getPhone() +"</td></tr>");
	}

	if (objCustomerInfo.getIsMailAddress()) {

		msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Mailing Address (if different) </b></td></tr>");

		if (!"".equals(Utility.checkNull(objCustomerInfo.getMailAddress()))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Street Address: </b><span style=\"color:red\">" + objCustomerInfo.getMailAddress() +"</span></td></tr>");
		}

		if (!"".equals(Utility.checkNull(objCustomerInfo.getMailAddress2()))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Street Address line 2: </b><span style=\"color:red\">" + objCustomerInfo.getMailAddress2() +"</span></td></tr>");
		}

		if (!"".equals(Utility.checkNull(objCustomerInfo.getMailCity()))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;City: </b><span style=\"color:red\">" + objCustomerInfo.getMailCity() +"</td></tr>");
		}

		if (!"".equals(Utility.checkNull(objCustomerInfo.getMailState()))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;State / Province: </b><span style=\"color:red\">" + objCustomerInfo.getMailState() +"</span></td></tr>");
		}

		if (!"".equals(Utility.checkNull(objCustomerInfo.getMailPostalCode()))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Postal / Zip Code: </b><span style=\"color:red\">" + objCustomerInfo.getMailPostalCode() +"</td></tr>");
		}

		if (!"".equals(Utility.checkNull(objCustomerInfo.getMailCountry()))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Country: </b><span style=\"color:red\">" + objCustomerInfo.getMailCountry() +"</span></td></tr>");
		}

		if (!"".equals(Utility.checkNull(objCustomerInfo.getMailPhone()))) {
			msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Phone: </b><span style=\"color:red\">" + objCustomerInfo.getMailPhone() +"</span></td></tr>");
		}
	}
	
	if (!"".equals(Utility.checkNull(objCustomerInfo.getCustInfo()))) {
		msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Contact Name: </b><span style=\"color:red\">" + objCustomerInfo.getCustInfo() +"</span></td></tr>");
	}

	if (!"".equals(Utility.checkNull(objCustomerInfo.getCustEmail()))) {
		msgBody.append("<tr><td  height=\"36\"><b>&nbsp;&nbsp;&nbsp;&nbsp;Contact Email: </b><a href=\""+"mailto:"+objCustomerInfo.getCustEmail()+"\" style=\"color:red\"><span style=\"color:red\">" + objCustomerInfo.getCustEmail() +"</span></a></td></tr>");
	}

	msgBody.append("</table>");

	msgBody.append("<h4>Regards,<br>HubCiti Team</h4>");
	msgBody.append("</body>");
	msgBody.append("</html>\n");
	msgBody.toString();
	return msgBody.toString();
}



/**
 * The method for forming HTML with retailer Info.
 * 
 * @param Item
 *            item object.
 * @return email template.
 */

public static String formShareAppNewsDetailHTML(List<Item> arNewsDetailList) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {
	LOG.info("Inside Utility : formShareAppInfoHTML ");
	final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
	emailTemplate.append("<body style='font-family:aerial;font-size:12px'> <h4> " + arNewsDetailList.get(0).getShareText() + "</h4>\n");
	emailTemplate.append("<table border=\"0\">");

	emailTemplate.append("<tr><td  height=\"36\"><b>News Title:</b> " + arNewsDetailList.get(0).getTitle() + "</td></tr>");

	//	emailTemplate.append("<tr><td  height=\"300\"><b>&nbsp;&nbsp;&nbsp;&nbsp;News Image:</b> <img height=\"250\" width=\"250\" src=\""+ arNewsDetailList.get(0).getImage()+ "\"/></td></tr>");

	if (null != arNewsDetailList.get(0).getQrUrl() && !"N/A".equals(arNewsDetailList.get(0).getQrUrl())) {
		emailTemplate.append("<tr><td height=\"36\"><b>Visit:</b> <a href=\""+Utility.getTinyURL(arNewsDetailList.get(0).getQrUrl()) +"\">" + Utility.getTinyURL(arNewsDetailList.get(0).getQrUrl()) + "</a></td></tr>");
	}
	emailTemplate.append("</table>");

	emailTemplate.append("<h4>More information at HubCiti <a href=\"http://hubciti.com\">http://hubciti.com</a></h4>");
	emailTemplate.append("</body>");
	emailTemplate.append("</html>\n");
	return emailTemplate.toString();
}


/**
 * The method for forming HTML with News Details Info.
 * 
 * @param Item
 *            item object.
 * @return email template.
 */

public static String formShareAppNewsDetailAndriodHTML(List<Item> arNewsDetailList) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException,
InvalidAlgorithmParameterException, InvalidKeySpecException, IllegalBlockSizeException, BadPaddingException {
	LOG.info("Inside Utility : formShareAppNewsDetailAndriodHTML ");
	final StringBuffer emailTemplate = new StringBuffer("<html><head></head>");
	emailTemplate.append("<body> <h4> " + arNewsDetailList.get(0).getShareText() + "</h4>\n");

	emailTemplate.append("<p><b>News Title:</b> " + arNewsDetailList.get(0).getTitle() + "</p>");

	//	emailTemplate.append("<tr><td  height=\"300\"><b>&nbsp;&nbsp;&nbsp;&nbsp;News Image:</b> <img height=\"250\" width=\"250\" src=\""+ arNewsDetailList.get(0).getImage()+ "\"/></td></tr>");

	if (null != arNewsDetailList.get(0).getQrUrl() && !"N/A".equals(arNewsDetailList.get(0).getQrUrl())) {
		emailTemplate.append("<p><b>Visit:</b> <a href=\""+Utility.getTinyURL(arNewsDetailList.get(0).getQrUrl()) +"\">" + Utility.getTinyURL(arNewsDetailList.get(0).getQrUrl()) + "</a></p>");
	}

	emailTemplate.append("<p> More information at HubCiti <a href=\"http://hubciti.com\">http://hubciti.com</a></p>");

	emailTemplate.append("</body>");
	emailTemplate.append("</html>\n");
	return emailTemplate.toString();
}
}
